task_tracker/task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from taskmanager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskmanager.urls')),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('create_user/', views.create_user, name= 'create_user'),
    path('crear_tarea', views.crear_tarea, name='crear_tarea'),
    path('ver_tarea/<int:task_id>', views.ver_tarea, name='ver_tarea'),
    path('tareas_pendientes/', views.listar_tareas_pendientes, name='listar_tareas_pendientes'),
    path('editar_tarea/<int:task_id>/', views.editar_tarea, name='editar_tarea'),
    path('eliminar_tarea/<int:task_id>/', views.eliminar_tarea, name='eliminar_tarea'),
    path('editar_observaciones/<int:task_id>/', views.editar_observaciones, name='editar_observaciones'),
    path('', views.index, name='index'),
]

task_tracker/taskmanager/urls.py
from django.urls import path
from . import views  # Importa las vistas de tu aplicación

urlpatterns = [

]

task_tracker/taskmanager/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Tag(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre

class Prioridad(models.Model):
    nombre = models.CharField(max_length=50)
    prioridad = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

class Task(models.Model):
    ESTADO_CHOICES = (
        ('pendiente', 'Pendiente'),
        ('en_progreso', 'En Progreso'),
        ('completada', 'Completada'),
    )

    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_vencimiento = models.DateTimeField(null=True, blank=True)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='pendiente')
    etiquetas = models.ManyToManyField(Tag, related_name='tareas')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    observaciones = models.TextField(blank=True, null=True)
    asignado_a = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tareas_asignadas', blank=True, null=True)
    prioridad = models.ForeignKey('Prioridad', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.titulo
    
class Observacion(models.Model):
    tarea = models.ForeignKey(Task, related_name='observaciones_task', on_delete=models.CASCADE)
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

task_tracker/taskmanager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Task, Tag, Prioridad

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'password1', 'password2']

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        max_length=254,
        label="Nombre de Usuario",  # Personaliza la etiqueta del campo de usuario
        widget=forms.TextInput(attrs={'autofocus': True})
    )
    password = forms.CharField(
        label="Contraseña",  # Personaliza la etiqueta del campo de contraseña
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
        error_messages={
            'invalid_login': 'Por favor, ingrese un nombre de usuario y contraseña válidos. Tenga en cuenta que ambos campos son sensibles a mayúsculas y minúsculas.',
            }
    )

class TaskForm(forms.ModelForm):
    etiquetas = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    # Agrega un campo para seleccionar la prioridad
    prioridad = forms.ModelChoiceField(
        queryset=Prioridad.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False,
    )

    class Meta:
        model = Task
        fields = ['titulo', 'descripcion', 'fecha_vencimiento', 'asignado_a', 'etiquetas', 'prioridad']

    widgets = {
        'fecha_vencimiento': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
    }

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['fecha_vencimiento'].widget.attrs.update({'class': 'datepicker'})

class TaskFilterForm(forms.Form):
    ESTADO_CHOICES = (
        ('pendiente', 'Pendiente'),
        ('en_progreso', 'En Progreso'),
        ('completada', 'Completada'),
    )
    estado = forms.ChoiceField(choices=Task.ESTADO_CHOICES, required=False)
    etiquetas = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    fecha_vencimiento = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))

class TaskEditForm(forms.ModelForm):
    prioridad = forms.ModelChoiceField(
        queryset=Prioridad.objects.all(),
        required=False,
    )

    class Meta:
        model = Task
        fields = ['titulo', 'descripcion', 'fecha_vencimiento', 'etiquetas', 'prioridad']

    widgets = {
        'fecha_vencimiento': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
    }

    def __init__(self, *args, **kwargs):
        super(TaskEditForm, self).__init__(*args, **kwargs)
        self.fields['fecha_vencimiento'].widget.attrs.update({'class': 'datepicker'})

task_tracker/taskmanager/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomAuthenticationForm, TaskForm, TaskFilterForm
from .models import Task,Observacion, Prioridad

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # Autenticar al usuario
            login(request, form.get_user())
            return redirect('listar_tareas_pendientes')  
    else:
        form = CustomAuthenticationForm()
    return render(request, 'taskmanager/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('index')  # Redirige al inicio de sesión.


def index(request):
    return render(request, 'taskmanager/index.html')

def create_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Inicia sesión automáticamente después de crear el usuario
            return redirect('listar_tareas_pendientes')  # Redirige a la página de inicio
    else:
        form = CustomUserCreationForm()
    return render(request, 'taskmanager/create_user.html', {'form': form})

@login_required
def listar_tareas_pendientes(request):
    tareas_pendientes = Task.objects.filter(usuario=request.user).order_by('fecha_vencimiento').prefetch_related('etiquetas')  # Usamos prefetch_related para cargar las etiquetas relacionadas
    if request.method == 'GET':
        form = TaskFilterForm(request.GET)
        if form.is_valid():
            estado = form.cleaned_data.get('estado')
            etiquetas = form.cleaned_data.get('etiquetas')
            fecha_vencimiento = form.cleaned_data.get('fecha_vencimiento')
            if estado:
                tareas_pendientes = tareas_pendientes.filter(estado=estado)
            if etiquetas:
                tareas_pendientes = tareas_pendientes.filter(etiquetas__in=etiquetas)
            if fecha_vencimiento:
                tareas_pendientes = tareas_pendientes.filter(fecha_vencimiento__date=fecha_vencimiento)
            
            if 'limpiar_filtros' in request.GET:
                return redirect('listar_tareas_pendientes')
    else:
        form = TaskFilterForm()
    return render(request, 'taskmanager/listar_tareas_pendientes.html', {'form': form, 'tareas_pendientes': tareas_pendientes})

@login_required
def crear_tarea(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            tarea = form.save(commit=False)
            tarea.asignado_a = form.cleaned_data['asignado_a']

            tarea.prioridad = form.cleaned_data['prioridad']
            
            tarea.usuario = request.user
            tarea.save()
            form.save_m2m()
            return redirect('listar_tareas_pendientes')
    else:
        form = TaskForm()
    return render(request, 'taskmanager/crear_tarea.html', {'form': form})


@login_required
def ver_tarea(request, task_id):
    tarea = get_object_or_404(Task, pk=task_id)
    etiquetas = tarea.etiquetas.all()
    prioridad = tarea.prioridad

    if request.method == 'POST':
        action = request.POST.get('action')
        if action == 'completar':
            tarea.estado = 'completada'
            tarea.save()
        elif action == 'eliminar':
            tarea.delete()
        elif action == 'guardar_observaciones':
            observaciones = request.POST.get('observaciones')
            Observacion.objects.create(tarea=tarea, texto=observaciones)
            # Redirige a la vista de visualización de tareas después de guardar observaciones
            return redirect('ver_tarea', task_id=task_id)

    tareas_ordenadas = Task.objects.filter(usuario=request.user).order_by('fecha_vencimiento').prefetch_related('etiquetas')
    observaciones_tarea = Observacion.objects.filter(tarea=tarea).order_by('-fecha_creacion')
    # Pasa las etiquetas y observaciones a la plantilla
    return render(request, 'taskmanager/ver_tarea.html', {'task': tarea, 'etiquetas': etiquetas, 'tareas_ordenadas': tareas_ordenadas, 'observaciones_tarea': observaciones_tarea, 'prioridad': prioridad})



@login_required
def editar_tarea(request, task_id):
    tarea = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=tarea)
        if form.is_valid():
            form.save()
            return redirect('ver_tarea', task_id=task_id)
    else:
        form = TaskForm(instance=tarea)
    return render(request, 'taskmanager/editar_tarea.html', {'form': form, 'task': tarea})


def eliminar_tarea(request, task_id):
    tarea = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        tarea.delete()
        return redirect('listar_tareas_pendientes')
    return render(request, 'taskmanager/listar_tareas_pendientes', {'task': tarea})

def editar_observaciones(request, task_id):
    tarea = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        observaciones = request.POST.get('observaciones')
        tarea.observaciones = observaciones
        tarea.save()
        return redirect('ver_tarea', task_id=task_id)
    return render(request, 'taskmanager/editar_observaciones.html', {'task': tarea})

task_tracker/task_tracker/templates/taskmanager/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
</head>
<header>
    {%block header%}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#"><i class="far fa-sticky-note" style="color: #ced4de;"></i> Task Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% if request.path == '/landing/' %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'index' %}">Home</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endblock%}
</header>
<body>
    {% block content%}
    {% endblock %}
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/296c253a12.js" crossorigin="anonymous"></script>
    
</body>
<footer>
    {% block footer %}
    <footer class="bg-dark text-white text-center py-3 fixed-bottom m-lg-3">
        <p>&copy; 2023 App</p>
    </footer>
    {% endblock%}
</footer>
</html>

task_tracker/task_tracker/templates/taskmanager/crear_tarea.html
{% extends "taskmanager/base.html" %}
{% block content %}
<div class="container mt-5">
    <h2>Crear Tarea</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.titulo.label_tag }}
        {{ form.titulo }}
        {{ form.descripcion.label_tag }}
        {{ form.descripcion }}
        {{ form.fecha_vencimiento.label_tag }}
        <input type="datetime-local" id="id_fecha_vencimiento" name="fecha_vencimiento" required placeholder="YYYY-MM-DDTHH:mm" value="{{ task.fecha_vencimiento|date:'Y-m-d\TH:i' }}">
        <div class="form-group">
            <label for="{{ form.asignado_a.id_for_label }}">Asignar a:</label>
            {{ form.asignado_a }}
        </div>
        <div class="form-check form-group">
            <label class="form-check-label" for="{{ form.prioridad.id_for_label }}">¿Prioridad?</label>
            {{ form.prioridad }}
        </div>
        {{ form.etiquetas.label_tag }}
        {{ form.etiquetas }}
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

task_tracker/task_tracker/templates/taskmanager/create_user.html
{% extends "taskmanager/base.html" %}
{% block content %}
<div class="container mt-5">
    <h2>Registrarse</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Crear Usuario</button>
    </form>
</div>
{% endblock %}

task_tracker/task_tracker/templates/taskmanager/editar_tarea.html
{% extends "taskmanager/base.html" %}
{% block content %}
<div class="container mt-5">
    <h2>Editar Tarea</h2>
    <form method="POST" action="{% url 'editar_tarea' task.id %}">
        {% csrf_token %}
        {{ form.titulo.label_tag }}
        {{ form.titulo }}
        {{ form.descripcion.label_tag }}
        {{ form.descripcion }}
        {{ form.fecha_vencimiento.label_tag }}
        <input type="datetime-local" id="id_fecha_vencimiento" name="fecha_vencimiento" required placeholder="YYYY-MM-DDTHH:mm" value="{{ task.fecha_vencimiento|date:'Y-m-d\TH:i' }}">

        <div class="form-check form-group">
            <label class="form-check-label" for="{{ form.prioridad.id_for_label }}">¿Prioridad?</label>
            {{ form.prioridad }}
        </div>
        
        {{ form.etiquetas.label_tag }}
        {{ form.etiquetas }}
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>
<a href="{% url 'listar_tareas_pendientes' %}" class="btn btn-secondary">Retornar</a>
{% endblock %}

task_tracker/task_tracker/templates/taskmanager/index.html
{% extends "taskmanager/base.html" %}
{% block content %}
    <h1>Bienvenido</h1>
    <a href="{% url 'login' %}" class="btn btn-primary">Iniciar Sesión</a>
    <a href="{% url 'create_user' %}" class="btn btn-primary">Registrarse</a>
{% endblock %}

task_tracker/task_tracker/templates/taskmanager/listar_tareas_pendientes.html
{% extends "taskmanager/base.html" %}

{% block content %}
<h2>Tareas Pendientes {{ user }}</h2>
<a href="{% url 'crear_tarea' %}" class="btn btn-primary">Agregar Tarea</a>

<form method="GET" action="{% url 'listar_tareas_pendientes' %}" class="form-inline mt-3">
    {{ form.estado.label_tag }}
    {{ form.estado }}
    {{ form.etiquetas.label_tag }}
    {{ form.etiquetas }}
    {{ form.fecha_vencimiento.label_tag }}
    {{ form.fecha_vencimiento }}
    <button type="submit" class="btn btn-primary">Filtrar</button>
    <a href="{% url 'listar_tareas_pendientes' %}" class="btn btn-secondary ml-2">Limpiar filtros</a>
</form>

<table class="table mt-3">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Descripción</th>
            <th>Fecha de Vencimiento</th>
            <th>Etiqueta</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for tarea in tareas_pendientes %}
        <tr>
            <td>{{ tarea.titulo }}</td>
            <td>{{ tarea.descripcion }}</td>
            <td>{{ tarea.fecha_vencimiento }}</td>
            <td>
                {% for etiqueta in tarea.etiquetas.all %}
                {{ etiqueta.nombre }}
                {% endfor %}
            </td>
            
            <td>
                {% if tarea.id %}
                <a href="{% url 'ver_tarea' tarea.id %}" class="btn btn-info">Ver</a>
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No hay tareas pendientes.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

task_tracker/task_tracker/templates/taskmanager/login.html
{% extends "taskmanager/base.html" %}
{% block content %}
<div class="container mt-5">
    <h2>Iniciar Sesión</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
    </form>
</div>
{% endblock %}

task_tracker/task_tracker/templates/taskmanager/ver_tarea.html
{% extends "taskmanager/base.html" %}
{% block content %}
<h1>Detalles de Tarea</h1>
<a href="{% url 'listar_tareas_pendientes' %}" class="btn btn-secondary">Retornar</a>
<br><br>
<h3>Prioridad:</h3>
{% if task.prioridad %}
    <p>Sí</p>
{% else %}
    <p>No</p>
{% endif %}
<br>
<table class="table">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Descripción</th>
            <th>Fecha de Vencimiento</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ task.titulo }}</td>
            <td>{{ task.descripcion }}</td>
            <td>{{ task.fecha_vencimiento }}</td>
            <td>{{ task.estado }}</td>
            <td>
                <form method="POST" action="{% url 'editar_tarea' task.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="editar">
                    <button type="submit" class="btn btn-primary">Editar</button>
                </form>
                {% if tarea.id %}
                    <a href="{% url 'editar_tarea' tarea.id %}">Editar Tarea</a>
                {% endif %}
                
                <form method="POST" onsubmit="return confirm('¿Estás seguro de que deseas eliminar esta tarea?');" action="{% url 'eliminar_tarea' task.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="eliminar">
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
                
                <form method="POST" action="{% url 'ver_tarea' task.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="completar">
                    <button type="submit" class="btn btn-success" {% if task.estado == 'completada' %}disabled{% endif %}>
                        {% if task.estado == 'completada' %}Completada{% else %}Completar{% endif %}
                    </button>
                </form>
            </td>
        </tr>
    </tbody>
</table>


<br><br>
<!-- Agregar un formulario para editar las observaciones -->
<div class="row">
    <div class="col-md-6">
        <form method="POST" action="{% url 'ver_tarea' task.id %}">
            {% csrf_token %}
            <input type="hidden" name="action" value="guardar_observaciones">
            <h3>Observaciones</h3>
            <textarea name="observaciones" rows="4" cols="50" class="form-control">{{ task.observaciones }}</textarea>
            <br>
            <button type="submit" class="btn btn-primary">Guardar Observaciones</button>
        </form>
    </div>

    <div class="col-md-6">
        <div class="observaciones-section">
            <h3>Historial de Observaciones</h3>
            <ul>
                {% for observacion in observaciones_tarea %}
                    <li>{{ observacion.fecha_creacion }}: {{ observacion.texto }}</li>
                {% empty %}
                    <li>No hay observaciones registradas.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>


{% endblock %}